import 'package:flutter/material.dart';
import 'package:sticky_header_reordering_list/sticky_header_reordering_list.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Sticky Header Reordering List Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      home: const HomePage(title: 'Sticky Header Reorder able List'),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key, required this.title});

  final String title;

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final List<Map<String, String>> movies = [
    {'title': 'Inception', 'genre': 'Sci-Fi'},
    {'title': 'The Dark Knight', 'genre': 'Action'},
    {'title': 'Interstellar', 'genre': 'Sci-Fi'},
    {'title': 'Pulp Fiction', 'genre': 'Crime'},
    {'title': 'Forrest Gump', 'genre': 'Drama'},
    {'title': 'The Shawshank Redemption', 'genre': 'Drama'},
    {'title': 'The Godfather', 'genre': 'Crime'},
    {'title': 'The Matrix', 'genre': 'Sci-Fi'},
    {'title': 'Gladiator', 'genre': 'Action'},
    {'title': 'Titanic', 'genre': 'Romance'},
    {'title': 'Avengers: Endgame', 'genre': 'Action'},
    {'title': 'The Lion King', 'genre': 'Animation'},
    {'title': 'Back to the Future', 'genre': 'Sci-Fi'},
    {'title': 'Jurassic Park', 'genre': 'Adventure'},
    {'title': 'Toy Story', 'genre': 'Animation'},
    {'title': 'Parasite', 'genre': 'Thriller'},
    {'title': 'The Silence of the Lambs', 'genre': 'Thriller'},
    {'title': "Schindler's List", 'genre': 'Historical Drama'},
    {'title': 'Coco', 'genre': 'Animation'},
    {'title': 'The Avengers', 'genre': 'Action'},
    {'title': 'Black Panther', 'genre': 'Action'},
    {'title': 'Avatar', 'genre': 'Sci-Fi'},
    {'title': 'Frozen', 'genre': 'Animation'},
    {'title': 'The Social Network', 'genre': 'Drama'},
    {'title': 'Mad Max: Fury Road', 'genre': 'Action'},
    {'title': 'The Wolf of Wall Street', 'genre': 'Biography'},
    {'title': 'Django Unchained', 'genre': 'Western'},
    {'title': 'Whiplash', 'genre': 'Drama'},
    {'title': 'The Grand Budapest Hotel', 'genre': 'Comedy'},
    {'title': 'Guardians of the Galaxy', 'genre': 'Action'},
    {'title': 'Spider-Man: No Way Home', 'genre': 'Action'},
    {'title': 'Finding Nemo', 'genre': 'Animation'},
    {'title': 'Up', 'genre': 'Animation'},
    {'title': 'The Incredibles', 'genre': 'Animation'},
    {'title': 'Ratatouille', 'genre': 'Animation'},
    {'title': 'Inside Out', 'genre': 'Animation'},
    {'title': 'Soul', 'genre': 'Animation'},
    {'title': 'Shrek', 'genre': 'Animation'},
    {
      'title': 'The Lord of the Rings: The Fellowship of the Ring',
      'genre': 'Fantasy'
    },
    {'title': 'The Lord of the Rings: The Two Towers', 'genre': 'Fantasy'},
    {
      'title': 'The Lord of the Rings: The Return of the King',
      'genre': 'Fantasy'
    },
    {'title': "Harry Potter and the Sorcerer's Stone", 'genre': 'Fantasy'},
    {'title': 'Harry Potter and the Chamber of Secrets', 'genre': 'Fantasy'},
    {'title': 'Harry Potter and the Prisoner of Azkaban', 'genre': 'Fantasy'},
    {'title': 'Harry Potter and the Goblet of Fire', 'genre': 'Fantasy'},
    {'title': 'Harry Potter and the Order of the Phoenix', 'genre': 'Fantasy'},
    {'title': 'Harry Potter and the Half-Blood Prince', 'genre': 'Fantasy'},
    {
      'title': 'Harry Potter and the Deathly Hallows: Part 1',
      'genre': 'Fantasy'
    },
    {
      'title': 'Harry Potter and the Deathly Hallows: Part 2',
      'genre': 'Fantasy'
    },
    {'title': 'Movie 1', 'genre': 'Genre 1'},
    {'title': 'Movie 2', 'genre': 'Genre 2'},
    {'title': 'Movie 3', 'genre': 'Genre 3'},
    {'title': 'Movie 4', 'genre': 'Genre 4'},
    {'title': 'Movie 5', 'genre': 'Genre 5'},
    {'title': 'Movie 6', 'genre': 'Genre 6'},
    {'title': 'Movie 7', 'genre': 'Genre 7'},
    {'title': 'Movie 8', 'genre': 'Genre 8'},
    {'title': 'Movie 9', 'genre': 'Genre 9'},
    {'title': 'Movie 10', 'genre': 'Genre 0'},
    {'title': 'Movie 11', 'genre': 'Genre 1'},
    {'title': 'Movie 12', 'genre': 'Genre 2'},
    {'title': 'Movie 13', 'genre': 'Genre 3'},
    {'title': 'Movie 14', 'genre': 'Genre 4'},
    {'title': 'Movie 15', 'genre': 'Genre 5'},
    {'title': 'Movie 16', 'genre': 'Genre 6'},
    {'title': 'Movie 17', 'genre': 'Genre 7'},
    {'title': 'Movie 18', 'genre': 'Genre 8'},
    {'title': 'Movie 19', 'genre': 'Genre 9'},
    {'title': 'Movie 20', 'genre': 'Genre 0'},
    {'title': 'Movie 21', 'genre': 'Genre 1'},
    {'title': 'Movie 22', 'genre': 'Genre 2'},
    {'title': 'Movie 23', 'genre': 'Genre 3'},
    {'title': 'Movie 24', 'genre': 'Genre 4'},
    {'title': 'Movie 25', 'genre': 'Genre 5'},
    {'title': 'Movie 26', 'genre': 'Genre 6'},
    {'title': 'Movie 27', 'genre': 'Genre 7'},
    {'title': 'Movie 28', 'genre': 'Genre 8'},
    {'title': 'Movie 29', 'genre': 'Genre 9'},
    {'title': 'Movie 30', 'genre': 'Genre 0'},
    {'title': 'Movie 31', 'genre': 'Genre 1'},
    {'title': 'Movie 32', 'genre': 'Genre 2'},
    {'title': 'Movie 33', 'genre': 'Genre 3'},
    {'title': 'Movie 34', 'genre': 'Genre 4'},
    {'title': 'Movie 35', 'genre': 'Genre 5'},
    {'title': 'Movie 36', 'genre': 'Genre 6'},
    {'title': 'Movie 37', 'genre': 'Genre 7'},
    {'title': 'Movie 38', 'genre': 'Genre 8'},
    {'title': 'Movie 39', 'genre': 'Genre 9'},
    {'title': 'Movie 40', 'genre': 'Genre 0'},
    {'title': 'Movie 41', 'genre': 'Genre 1'},
    {'title': 'Movie 42', 'genre': 'Genre 2'},
    {'title': 'Movie 43', 'genre': 'Genre 3'},
    {'title': 'Movie 44', 'genre': 'Genre 4'},
    {'title': 'Movie 45', 'genre': 'Genre 5'},
    {'title': 'Movie 46', 'genre': 'Genre 6'},
    {'title': 'Movie 47', 'genre': 'Genre 7'},
    {'title': 'Movie 48', 'genre': 'Genre 8'},
    {'title': 'Movie 49', 'genre': 'Genre 9'},
    {'title': 'Movie 50', 'genre': 'Genre 0'},
    {'title': 'Movie 51', 'genre': 'Genre 1'},
    {'title': 'Movie 52', 'genre': 'Genre 2'},
    {'title': 'Movie 53', 'genre': 'Genre 3'},
    {'title': 'Movie 54', 'genre': 'Genre 4'},
    {'title': 'Movie 55', 'genre': 'Genre 5'},
    {'title': 'Movie 56', 'genre': 'Genre 6'},
    {'title': 'Movie 57', 'genre': 'Genre 7'},
    {'title': 'Movie 58', 'genre': 'Genre 8'},
    {'title': 'Movie 59', 'genre': 'Genre 9'},
    {'title': 'Movie 60', 'genre': 'Genre 0'},
    {'title': 'Movie 61', 'genre': 'Genre 1'},
    {'title': 'Movie 62', 'genre': 'Genre 2'},
    {'title': 'Movie 63', 'genre': 'Genre 3'},
    {'title': 'Movie 64', 'genre': 'Genre 4'},
    {'title': 'Movie 65', 'genre': 'Genre 5'},
    {'title': 'Movie 66', 'genre': 'Genre 6'},
    {'title': 'Movie 67', 'genre': 'Genre 7'},
    {'title': 'Movie 68', 'genre': 'Genre 8'},
    {'title': 'Movie 69', 'genre': 'Genre 9'},
    {'title': 'Movie 70', 'genre': 'Genre 0'},
    {'title': 'Movie 71', 'genre': 'Genre 1'},
    {'title': 'Movie 72', 'genre': 'Genre 2'},
    {'title': 'Movie 73', 'genre': 'Genre 3'},
    {'title': 'Movie 74', 'genre': 'Genre 4'},
    {'title': 'Movie 75', 'genre': 'Genre 5'},
    {'title': 'Movie 76', 'genre': 'Genre 6'},
    {'title': 'Movie 77', 'genre': 'Genre 7'},
    {'title': 'Movie 78', 'genre': 'Genre 8'},
    {'title': 'Movie 79', 'genre': 'Genre 9'},
    {'title': 'Movie 80', 'genre': 'Genre 0'},
    {'title': 'Movie 81', 'genre': 'Genre 1'},
    {'title': 'Movie 82', 'genre': 'Genre 2'},
    {'title': 'Movie 83', 'genre': 'Genre 3'},
    {'title': 'Movie 84', 'genre': 'Genre 4'},
    {'title': 'Movie 85', 'genre': 'Genre 5'},
    {'title': 'Movie 86', 'genre': 'Genre 6'},
    {'title': 'Movie 87', 'genre': 'Genre 7'},
    {'title': 'Movie 88', 'genre': 'Genre 8'},
    {'title': 'Movie 89', 'genre': 'Genre 9'},
    {'title': 'Movie 90', 'genre': 'Genre 0'},
    {'title': 'Movie 91', 'genre': 'Genre 1'},
    {'title': 'Movie 92', 'genre': 'Genre 2'},
    {'title': 'Movie 93', 'genre': 'Genre 3'},
    {'title': 'Movie 94', 'genre': 'Genre 4'},
    {'title': 'Movie 95', 'genre': 'Genre 5'},
    {'title': 'Movie 96', 'genre': 'Genre 6'},
    {'title': 'Movie 97', 'genre': 'Genre 7'},
    {'title': 'Movie 98', 'genre': 'Genre 8'},
    {'title': 'Movie 99', 'genre': 'Genre 9'},
    {'title': 'Movie 100', 'genre': 'Genre 0'},
    {'title': 'Movie 101', 'genre': 'Genre 1'},
    {'title': 'Movie 102', 'genre': 'Genre 2'},
    {'title': 'Movie 103', 'genre': 'Genre 3'},
    {'title': 'Movie 104', 'genre': 'Genre 4'},
    {'title': 'Movie 105', 'genre': 'Genre 5'},
    {'title': 'Movie 106', 'genre': 'Genre 6'},
    {'title': 'Movie 107', 'genre': 'Genre 7'},
    {'title': 'Movie 108', 'genre': 'Genre 8'},
    {'title': 'Movie 109', 'genre': 'Genre 9'},
    {'title': 'Movie 110', 'genre': 'Genre 0'},
    {'title': 'Movie 111', 'genre': 'Genre 1'},
    {'title': 'Movie 112', 'genre': 'Genre 2'},
    {'title': 'Movie 113', 'genre': 'Genre 3'},
    {'title': 'Movie 114', 'genre': 'Genre 4'},
    {'title': 'Movie 115', 'genre': 'Genre 5'},
    {'title': 'Movie 116', 'genre': 'Genre 6'},
    {'title': 'Movie 117', 'genre': 'Genre 7'},
    {'title': 'Movie 118', 'genre': 'Genre 8'},
    {'title': 'Movie 119', 'genre': 'Genre 9'},
    {'title': 'Movie 120', 'genre': 'Genre 0'},
    {'title': 'Movie 121', 'genre': 'Genre 1'},
    {'title': 'Movie 122', 'genre': 'Genre 2'},
    {'title': 'Movie 123', 'genre': 'Genre 3'},
    {'title': 'Movie 124', 'genre': 'Genre 4'},
    {'title': 'Movie 125', 'genre': 'Genre 5'},
    {'title': 'Movie 126', 'genre': 'Genre 6'},
    {'title': 'Movie 127', 'genre': 'Genre 7'},
    {'title': 'Movie 128', 'genre': 'Genre 8'},
    {'title': 'Movie 129', 'genre': 'Genre 9'},
    {'title': 'Movie 130', 'genre': 'Genre 0'},
    {'title': 'Movie 131', 'genre': 'Genre 1'},
    {'title': 'Movie 132', 'genre': 'Genre 2'},
    {'title': 'Movie 133', 'genre': 'Genre 3'},
    {'title': 'Movie 134', 'genre': 'Genre 4'},
    {'title': 'Movie 135', 'genre': 'Genre 5'},
    {'title': 'Movie 136', 'genre': 'Genre 6'},
    {'title': 'Movie 137', 'genre': 'Genre 7'},
    {'title': 'Movie 138', 'genre': 'Genre 8'},
    {'title': 'Movie 139', 'genre': 'Genre 9'},
    {'title': 'Movie 140', 'genre': 'Genre 0'},
    {'title': 'Movie 141', 'genre': 'Genre 1'},
    {'title': 'Movie 142', 'genre': 'Genre 2'},
    {'title': 'Movie 143', 'genre': 'Genre 3'},
    {'title': 'Movie 144', 'genre': 'Genre 4'},
    {'title': 'Movie 145', 'genre': 'Genre 5'},
    {'title': 'Movie 146', 'genre': 'Genre 6'},
    {'title': 'Movie 147', 'genre': 'Genre 7'},
    {'title': 'Movie 148', 'genre': 'Genre 8'},
    {'title': 'Movie 149', 'genre': 'Genre 9'},
    {'title': 'Movie 150', 'genre': 'Genre 0'},
    {'title': 'Movie 151', 'genre': 'Genre 1'},
    {'title': 'Movie 152', 'genre': 'Genre 2'},
    {'title': 'Movie 153', 'genre': 'Genre 3'},
    {'title': 'Movie 154', 'genre': 'Genre 4'},
    {'title': 'Movie 155', 'genre': 'Genre 5'},
    {'title': 'Movie 156', 'genre': 'Genre 6'},
    {'title': 'Movie 157', 'genre': 'Genre 7'},
    {'title': 'Movie 158', 'genre': 'Genre 8'},
    {'title': 'Movie 159', 'genre': 'Genre 9'},
    {'title': 'Movie 160', 'genre': 'Genre 0'},
    {'title': 'Movie 161', 'genre': 'Genre 1'},
    {'title': 'Movie 162', 'genre': 'Genre 2'},
    {'title': 'Movie 163', 'genre': 'Genre 3'},
    {'title': 'Movie 164', 'genre': 'Genre 4'},
    {'title': 'Movie 165', 'genre': 'Genre 5'},
    {'title': 'Movie 166', 'genre': 'Genre 6'},
    {'title': 'Movie 167', 'genre': 'Genre 7'},
    {'title': 'Movie 168', 'genre': 'Genre 8'},
    {'title': 'Movie 169', 'genre': 'Genre 9'},
    {'title': 'Movie 170', 'genre': 'Genre 0'},
    {'title': 'Movie 171', 'genre': 'Genre 1'},
    {'title': 'Movie 172', 'genre': 'Genre 2'},
    {'title': 'Movie 173', 'genre': 'Genre 3'},
    {'title': 'Movie 174', 'genre': 'Genre 4'},
    {'title': 'Movie 175', 'genre': 'Genre 5'},
    {'title': 'Movie 176', 'genre': 'Genre 6'},
    {'title': 'Movie 177', 'genre': 'Genre 7'},
    {'title': 'Movie 178', 'genre': 'Genre 8'},
    {'title': 'Movie 179', 'genre': 'Genre 9'},
    {'title': 'Movie 180', 'genre': 'Genre 0'},
    {'title': 'Movie 181', 'genre': 'Genre 1'},
    {'title': 'Movie 182', 'genre': 'Genre 2'},
    {'title': 'Movie 183', 'genre': 'Genre 3'},
    {'title': 'Movie 184', 'genre': 'Genre 4'},
    {'title': 'Movie 185', 'genre': 'Genre 5'},
    {'title': 'Movie 186', 'genre': 'Genre 6'},
    {'title': 'Movie 187', 'genre': 'Genre 7'},
    {'title': 'Movie 188', 'genre': 'Genre 8'},
    {'title': 'Movie 189', 'genre': 'Genre 9'},
    {'title': 'Movie 190', 'genre': 'Genre 0'},
    {'title': 'Movie 191', 'genre': 'Genre 1'},
    {'title': 'Movie 192', 'genre': 'Genre 2'},
    {'title': 'Movie 193', 'genre': 'Genre 3'},
    {'title': 'Movie 194', 'genre': 'Genre 4'},
    {'title': 'Movie 195', 'genre': 'Genre 5'},
    {'title': 'Movie 196', 'genre': 'Genre 6'},
    {'title': 'Movie 197', 'genre': 'Genre 7'},
    {'title': 'Movie 198', 'genre': 'Genre 8'},
    {'title': 'Movie 199', 'genre': 'Genre 9'},
    {'title': 'Movie 200', 'genre': 'Genre 0'},
    {'title': 'Movie 201', 'genre': 'Genre 1'},
    {'title': 'Movie 202', 'genre': 'Genre 2'},
    {'title': 'Movie 203', 'genre': 'Genre 3'},
    {'title': 'Movie 204', 'genre': 'Genre 4'},
    {'title': 'Movie 205', 'genre': 'Genre 5'},
    {'title': 'Movie 206', 'genre': 'Genre 6'},
    {'title': 'Movie 207', 'genre': 'Genre 7'},
    {'title': 'Movie 208', 'genre': 'Genre 8'},
    {'title': 'Movie 209', 'genre': 'Genre 9'},
    {'title': 'Movie 210', 'genre': 'Genre 0'},
    {'title': 'Movie 211', 'genre': 'Genre 1'},
    {'title': 'Movie 212', 'genre': 'Genre 2'},
    {'title': 'Movie 213', 'genre': 'Genre 3'},
    {'title': 'Movie 214', 'genre': 'Genre 4'},
    {'title': 'Movie 215', 'genre': 'Genre 5'},
    {'title': 'Movie 216', 'genre': 'Genre 6'},
    {'title': 'Movie 217', 'genre': 'Genre 7'},
    {'title': 'Movie 218', 'genre': 'Genre 8'},
    {'title': 'Movie 219', 'genre': 'Genre 9'},
    {'title': 'Movie 220', 'genre': 'Genre 0'},
    {'title': 'Movie 221', 'genre': 'Genre 1'},
    {'title': 'Movie 222', 'genre': 'Genre 2'},
    {'title': 'Movie 223', 'genre': 'Genre 3'},
    {'title': 'Movie 224', 'genre': 'Genre 4'},
    {'title': 'Movie 225', 'genre': 'Genre 5'},
    {'title': 'Movie 226', 'genre': 'Genre 6'},
    {'title': 'Movie 227', 'genre': 'Genre 7'},
    {'title': 'Movie 228', 'genre': 'Genre 8'},
    {'title': 'Movie 229', 'genre': 'Genre 9'},
    {'title': 'Movie 230', 'genre': 'Genre 0'},
    {'title': 'Movie 231', 'genre': 'Genre 1'},
    {'title': 'Movie 232', 'genre': 'Genre 2'},
    {'title': 'Movie 233', 'genre': 'Genre 3'},
    {'title': 'Movie 234', 'genre': 'Genre 4'},
    {'title': 'Movie 235', 'genre': 'Genre 5'},
    {'title': 'Movie 236', 'genre': 'Genre 6'},
    {'title': 'Movie 237', 'genre': 'Genre 7'},
    {'title': 'Movie 238', 'genre': 'Genre 8'},
    {'title': 'Movie 239', 'genre': 'Genre 9'},
    {'title': 'Movie 240', 'genre': 'Genre 0'},
    {'title': 'Movie 241', 'genre': 'Genre 1'},
    {'title': 'Movie 242', 'genre': 'Genre 2'},
    {'title': 'Movie 243', 'genre': 'Genre 3'},
    {'title': 'Movie 244', 'genre': 'Genre 4'},
    {'title': 'Movie 245', 'genre': 'Genre 5'},
    {'title': 'Movie 246', 'genre': 'Genre 6'},
    {'title': 'Movie 247', 'genre': 'Genre 7'},
    {'title': 'Movie 248', 'genre': 'Genre 8'},
    {'title': 'Movie 249', 'genre': 'Genre 9'},
    {'title': 'Movie 250', 'genre': 'Genre 0'},
    {'title': 'Movie 251', 'genre': 'Genre 1'},
    {'title': 'Movie 252', 'genre': 'Genre 2'},
    {'title': 'Movie 253', 'genre': 'Genre 3'},
    {'title': 'Movie 254', 'genre': 'Genre 4'},
    {'title': 'Movie 255', 'genre': 'Genre 5'},
    {'title': 'Movie 256', 'genre': 'Genre 6'},
    {'title': 'Movie 257', 'genre': 'Genre 7'},
    {'title': 'Movie 258', 'genre': 'Genre 8'},
    {'title': 'Movie 259', 'genre': 'Genre 9'},
    {'title': 'Movie 260', 'genre': 'Genre 0'},
    {'title': 'Movie 261', 'genre': 'Genre 1'},
    {'title': 'Movie 262', 'genre': 'Genre 2'},
    {'title': 'Movie 263', 'genre': 'Genre 3'},
    {'title': 'Movie 264', 'genre': 'Genre 4'},
    {'title': 'Movie 265', 'genre': 'Genre 5'},
    {'title': 'Movie 266', 'genre': 'Genre 6'},
    {'title': 'Movie 267', 'genre': 'Genre 7'},
    {'title': 'Movie 268', 'genre': 'Genre 8'},
    {'title': 'Movie 269', 'genre': 'Genre 9'},
    {'title': 'Movie 270', 'genre': 'Genre 0'},
    {'title': 'Movie 271', 'genre': 'Genre 1'},
    {'title': 'Movie 272', 'genre': 'Genre 2'},
    {'title': 'Movie 273', 'genre': 'Genre 3'},
    {'title': 'Movie 274', 'genre': 'Genre 4'},
    {'title': 'Movie 275', 'genre': 'Genre 5'},
    {'title': 'Movie 276', 'genre': 'Genre 6'},
    {'title': 'Movie 277', 'genre': 'Genre 7'},
    {'title': 'Movie 278', 'genre': 'Genre 8'},
    {'title': 'Movie 279', 'genre': 'Genre 9'},
    {'title': 'Movie 280', 'genre': 'Genre 0'},
    {'title': 'Movie 281', 'genre': 'Genre 1'},
    {'title': 'Movie 282', 'genre': 'Genre 2'},
    {'title': 'Movie 283', 'genre': 'Genre 3'},
    {'title': 'Movie 284', 'genre': 'Genre 4'},
    {'title': 'Movie 285', 'genre': 'Genre 5'},
    {'title': 'Movie 286', 'genre': 'Genre 6'},
    {'title': 'Movie 287', 'genre': 'Genre 7'},
    {'title': 'Movie 288', 'genre': 'Genre 8'},
    {'title': 'Movie 289', 'genre': 'Genre 9'},
    {'title': 'Movie 290', 'genre': 'Genre 0'},
    {'title': 'Movie 291', 'genre': 'Genre 1'},
    {'title': 'Movie 292', 'genre': 'Genre 2'},
    {'title': 'Movie 293', 'genre': 'Genre 3'},
    {'title': 'Movie 294', 'genre': 'Genre 4'},
    {'title': 'Movie 295', 'genre': 'Genre 5'},
    {'title': 'Movie 296', 'genre': 'Genre 6'},
    {'title': 'Movie 297', 'genre': 'Genre 7'},
    {'title': 'Movie 298', 'genre': 'Genre 8'},
    {'title': 'Movie 299', 'genre': 'Genre 9'},
    {'title': 'Movie 300', 'genre': 'Genre 0'},
    {'title': 'Movie 301', 'genre': 'Genre 1'},
    {'title': 'Movie 302', 'genre': 'Genre 2'},
    {'title': 'Movie 303', 'genre': 'Genre 3'},
    {'title': 'Movie 304', 'genre': 'Genre 4'},
    {'title': 'Movie 305', 'genre': 'Genre 5'},
    {'title': 'Movie 306', 'genre': 'Genre 6'},
    {'title': 'Movie 307', 'genre': 'Genre 7'},
    {'title': 'Movie 308', 'genre': 'Genre 8'},
    {'title': 'Movie 309', 'genre': 'Genre 9'},
    {'title': 'Movie 310', 'genre': 'Genre 0'},
    {'title': 'Movie 311', 'genre': 'Genre 1'},
    {'title': 'Movie 312', 'genre': 'Genre 2'},
    {'title': 'Movie 313', 'genre': 'Genre 3'},
    {'title': 'Movie 314', 'genre': 'Genre 4'},
    {'title': 'Movie 315', 'genre': 'Genre 5'},
    {'title': 'Movie 316', 'genre': 'Genre 6'},
    {'title': 'Movie 317', 'genre': 'Genre 7'},
    {'title': 'Movie 318', 'genre': 'Genre 8'},
    {'title': 'Movie 319', 'genre': 'Genre 9'},
    {'title': 'Movie 320', 'genre': 'Genre 0'},
    {'title': 'Movie 321', 'genre': 'Genre 1'},
    {'title': 'Movie 322', 'genre': 'Genre 2'},
    {'title': 'Movie 323', 'genre': 'Genre 3'},
    {'title': 'Movie 324', 'genre': 'Genre 4'},
    {'title': 'Movie 325', 'genre': 'Genre 5'},
    {'title': 'Movie 326', 'genre': 'Genre 6'},
    {'title': 'Movie 327', 'genre': 'Genre 7'},
    {'title': 'Movie 328', 'genre': 'Genre 8'},
    {'title': 'Movie 329', 'genre': 'Genre 9'},
    {'title': 'Movie 330', 'genre': 'Genre 0'},
    {'title': 'Movie 331', 'genre': 'Genre 1'},
    {'title': 'Movie 332', 'genre': 'Genre 2'},
    {'title': 'Movie 333', 'genre': 'Genre 3'},
    {'title': 'Movie 334', 'genre': 'Genre 4'},
    {'title': 'Movie 335', 'genre': 'Genre 5'},
    {'title': 'Movie 336', 'genre': 'Genre 6'},
    {'title': 'Movie 337', 'genre': 'Genre 7'},
    {'title': 'Movie 338', 'genre': 'Genre 8'},
    {'title': 'Movie 339', 'genre': 'Genre 9'},
    {'title': 'Movie 340', 'genre': 'Genre 0'},
    {'title': 'Movie 341', 'genre': 'Genre 1'},
    {'title': 'Movie 342', 'genre': 'Genre 2'},
    {'title': 'Movie 343', 'genre': 'Genre 3'},
    {'title': 'Movie 344', 'genre': 'Genre 4'},
    {'title': 'Movie 345', 'genre': 'Genre 5'},
    {'title': 'Movie 346', 'genre': 'Genre 6'},
    {'title': 'Movie 347', 'genre': 'Genre 7'},
    {'title': 'Movie 348', 'genre': 'Genre 8'},
    {'title': 'Movie 349', 'genre': 'Genre 9'},
    {'title': 'Movie 350', 'genre': 'Genre 0'},
    {'title': 'Movie 351', 'genre': 'Genre 1'},
    {'title': 'Movie 352', 'genre': 'Genre 2'},
    {'title': 'Movie 353', 'genre': 'Genre 3'},
    {'title': 'Movie 354', 'genre': 'Genre 4'},
    {'title': 'Movie 355', 'genre': 'Genre 5'},
    {'title': 'Movie 356', 'genre': 'Genre 6'},
    {'title': 'Movie 357', 'genre': 'Genre 7'},
    {'title': 'Movie 358', 'genre': 'Genre 8'},
    {'title': 'Movie 359', 'genre': 'Genre 9'},
    {'title': 'Movie 360', 'genre': 'Genre 0'},
    {'title': 'Movie 361', 'genre': 'Genre 1'},
    {'title': 'Movie 362', 'genre': 'Genre 2'},
    {'title': 'Movie 363', 'genre': 'Genre 3'},
    {'title': 'Movie 364', 'genre': 'Genre 4'},
    {'title': 'Movie 365', 'genre': 'Genre 5'},
    {'title': 'Movie 366', 'genre': 'Genre 6'},
    {'title': 'Movie 367', 'genre': 'Genre 7'},
    {'title': 'Movie 368', 'genre': 'Genre 8'},
    {'title': 'Movie 369', 'genre': 'Genre 9'},
    {'title': 'Movie 370', 'genre': 'Genre 0'},
    {'title': 'Movie 371', 'genre': 'Genre 1'},
    {'title': 'Movie 372', 'genre': 'Genre 2'},
    {'title': 'Movie 373', 'genre': 'Genre 3'},
    {'title': 'Movie 374', 'genre': 'Genre 4'},
    {'title': 'Movie 375', 'genre': 'Genre 5'},
    {'title': 'Movie 376', 'genre': 'Genre 6'},
    {'title': 'Movie 377', 'genre': 'Genre 7'},
    {'title': 'Movie 378', 'genre': 'Genre 8'},
    {'title': 'Movie 379', 'genre': 'Genre 9'},
    {'title': 'Movie 380', 'genre': 'Genre 0'},
    {'title': 'Movie 381', 'genre': 'Genre 1'},
    {'title': 'Movie 382', 'genre': 'Genre 2'},
    {'title': 'Movie 383', 'genre': 'Genre 3'},
    {'title': 'Movie 384', 'genre': 'Genre 4'},
    {'title': 'Movie 385', 'genre': 'Genre 5'},
    {'title': 'Movie 386', 'genre': 'Genre 6'},
    {'title': 'Movie 387', 'genre': 'Genre 7'},
    {'title': 'Movie 388', 'genre': 'Genre 8'},
    {'title': 'Movie 389', 'genre': 'Genre 9'},
    {'title': 'Movie 390', 'genre': 'Genre 0'},
    {'title': 'Movie 391', 'genre': 'Genre 1'},
    {'title': 'Movie 392', 'genre': 'Genre 2'},
    {'title': 'Movie 393', 'genre': 'Genre 3'},
    {'title': 'Movie 394', 'genre': 'Genre 4'},
    {'title': 'Movie 395', 'genre': 'Genre 5'},
    {'title': 'Movie 396', 'genre': 'Genre 6'},
    {'title': 'Movie 397', 'genre': 'Genre 7'},
    {'title': 'Movie 398', 'genre': 'Genre 8'},
    {'title': 'Movie 399', 'genre': 'Genre 9'},
    {'title': 'Movie 400', 'genre': 'Genre 0'},
    {'title': 'Movie 401', 'genre': 'Genre 1'},
    {'title': 'Movie 402', 'genre': 'Genre 2'},
    {'title': 'Movie 403', 'genre': 'Genre 3'},
    {'title': 'Movie 404', 'genre': 'Genre 4'},
    {'title': 'Movie 405', 'genre': 'Genre 5'},
    {'title': 'Movie 406', 'genre': 'Genre 6'},
    {'title': 'Movie 407', 'genre': 'Genre 7'},
    {'title': 'Movie 408', 'genre': 'Genre 8'},
    {'title': 'Movie 409', 'genre': 'Genre 9'},
    {'title': 'Movie 410', 'genre': 'Genre 0'},
    {'title': 'Movie 411', 'genre': 'Genre 1'},
    {'title': 'Movie 412', 'genre': 'Genre 2'},
    {'title': 'Movie 413', 'genre': 'Genre 3'},
    {'title': 'Movie 414', 'genre': 'Genre 4'},
    {'title': 'Movie 415', 'genre': 'Genre 5'},
    {'title': 'Movie 416', 'genre': 'Genre 6'},
    {'title': 'Movie 417', 'genre': 'Genre 7'},
    {'title': 'Movie 418', 'genre': 'Genre 8'},
    {'title': 'Movie 419', 'genre': 'Genre 9'},
    {'title': 'Movie 420', 'genre': 'Genre 0'},
    {'title': 'Movie 421', 'genre': 'Genre 1'},
    {'title': 'Movie 422', 'genre': 'Genre 2'},
    {'title': 'Movie 423', 'genre': 'Genre 3'},
    {'title': 'Movie 424', 'genre': 'Genre 4'},
    {'title': 'Movie 425', 'genre': 'Genre 5'},
    {'title': 'Movie 426', 'genre': 'Genre 6'},
    {'title': 'Movie 427', 'genre': 'Genre 7'},
    {'title': 'Movie 428', 'genre': 'Genre 8'},
    {'title': 'Movie 429', 'genre': 'Genre 9'},
    {'title': 'Movie 430', 'genre': 'Genre 0'},
    {'title': 'Movie 431', 'genre': 'Genre 1'},
    {'title': 'Movie 432', 'genre': 'Genre 2'},
    {'title': 'Movie 433', 'genre': 'Genre 3'},
    {'title': 'Movie 434', 'genre': 'Genre 4'},
    {'title': 'Movie 435', 'genre': 'Genre 5'},
    {'title': 'Movie 436', 'genre': 'Genre 6'},
    {'title': 'Movie 437', 'genre': 'Genre 7'},
    {'title': 'Movie 438', 'genre': 'Genre 8'},
    {'title': 'Movie 439', 'genre': 'Genre 9'},
    {'title': 'Movie 440', 'genre': 'Genre 0'},
    {'title': 'Movie 441', 'genre': 'Genre 1'},
    {'title': 'Movie 442', 'genre': 'Genre 2'},
    {'title': 'Movie 443', 'genre': 'Genre 3'},
    {'title': 'Movie 444', 'genre': 'Genre 4'},
    {'title': 'Movie 445', 'genre': 'Genre 5'},
    {'title': 'Movie 446', 'genre': 'Genre 6'},
    {'title': 'Movie 447', 'genre': 'Genre 7'},
    {'title': 'Movie 448', 'genre': 'Genre 8'},
    {'title': 'Movie 449', 'genre': 'Genre 9'},
    {'title': 'Movie 450', 'genre': 'Genre 0'},
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        backgroundColor: Colors.white,
        title: Text(
          widget.title,
          style: const TextStyle(color: Colors.blue),
        ),
      ),
      body: SafeArea(
        child: StickyHeaderReorderingList<Map<String, String>>(
          items: movies,
          sectionExtractor: (item) => item["genre"] ?? "",
          headerBuilder: (context, section) => Container(
            color: Colors.blue[400],
            padding: const EdgeInsets.all(8.0),
            child: Text(
              section,
              style: const TextStyle(
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
          ),
          itemBuilder: (context, item) => Column(
            children: [
              ListTile(
                title: Text(item["title"] ?? "Unknown"),
              ),
            ],
          ),
          isReordering: true,
          onReorderElements:
              (data, oldItem, newItem, newIndex, oldIndex, groupedItems) {
            print("Reordered: $oldItem -> $newItem");
          },
        ),
      ),
    );
  }
}
